apiVersion: v1
kind: Pod
metadata:
  name: goapp-memhigh
spec:
  nodeSelector:
    memsize: "high"
  containers:
  - image: dangtong/goapp
    name: goapp-memhigh
    ports:
    - containerPort: 8080
      protocol: TCP
