apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: nodeapp-deploy 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: nodeapp-pod 
  template: 
    metadata: 
      labels: 
        app: nodeapp-pod
    spec: 
      containers: 
      - name: nodeapp-container 
        image: dangtong/nodeapp 
        ports: 
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata: 
  name: nodeapp-service 
spec: 
  ports: 
  - port: 80 
    targetPort: 8080 
  selector: 
    app: nodeapp-pod
